[add] 프로젝트 구조에 맞게 폴더링 작업 및 디자인 에셋을 추가했습니다.
boostcampwm-2024/iOS03-SniffMeet pull request #10
Opened 2024-11-05 16:31 UTC by soletree

### 🔖  Issue Number

close #9 

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역을 적어주세요.
> 
- VIPER + Repository 구조에 맞게 폴더 구조를 변경했습니다. 
크게 Source / Resource로 나누었습니다. 소스코드와 관련없는 폰트 파일, 로티 파일 등은 Resource 폴더에 옮기시면 됩니다. 

아래와 같이 Scene 단위로 큰 틀을 잡아 폴더링 진행했습니다. 

![image](https://github.com/user-attachments/assets/25dd4ece-06fa-4ec5-a0e7-598e43366de3)

각각에 대해 View, Interactor, Presenter, Entity, Router로 나눕니다. 

![image](https://github.com/user-attachments/assets/6b046098-2a16-4369-b94c-3292272370e8)

- 앱 아이콘을 추가했습니다. 
- 이미지 플레이스 홀더를 추가했습니다.  (ImagePlaceholder)

2024-11-05 17:55 UTC, Kelly-Chui requested changes
수고하셨습니다 👍

2024-11-05 17:55 UTC, Kelly-Chui commented on SniffMeet/SniffMeet/Resource/Assets.xcassets/ImagePlaceholder.imageset/image-placeholder.png
png 포맷보다는 벡터 이미지로 사용하는게 어떤가요?
![Clip path group](https://github.com/user-attachments/assets/4e0373d3-5d02-4a63-a5ea-a375b38b77be)

2024-11-06 01:05 UTC, green-yoon87 approved these changes
오 Scene 단위로 나누어서 폴더링 진행하셨군요! 수고하셨습니당!

2024-11-06 01:05 UTC, green-yoon87 commented on SniffMeet/SniffMeet/Resource/Assets.xcassets/ImagePlaceholder.imageset/image-placeholder.png
백터 이미지로 바꾸는 이유도 함께 작성해주시면 좋을 거 같네요!

2024-11-06 02:01 UTC, Kelly-Chui approved these changes

2024-11-06 07:51 UTC, merged