[feat] supabase 디렉토리 및 Auth 기능 추가
boostcampwm-2024/iOS03-SniffMeet pull request #62
Opened 2024-11-18 19:15 UTC by Kelly-Chui

### 🔖  Issue Number

close #48 

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역을 적어주세요.
> 
- [X]  Supabase 디렉토리 추가
- [X]  익명 로그인 추가
    - [X]  세션 복원 추가
    - [ ]  세션 갱신 추가 

### 📝 PR 특이사항 

> PR을 볼 때 팀원에게 알려야 할 특이사항을 알려주세요.
> 
- 세션을 어떻게 관리해야 할까요?
    - 토큰이 만료되면 자동으로 갱신되도록 하는게 좋은 것 같습니다. 현재 세션을 `SupabaseConfig`이 들고 있는데, 싱글톤 객체가 서로를 호출하는 상황이 안전한가 고민중입니다.
    - `Session Manager`를 따로 만들까 고민중에 있습니다.
- 로그인을 해도 정보는 DB에서 불러옵니다. 현재 Auth의 상태를 컴바인으로 퍼블리쉬 하고, 이를 구독하여 DB에서 정보를 불러오는 로직이 필요할 것 같습니다.

2024-11-19 05:01 UTC, soletree requested changes
고생많으셨습니다~~~👍👍

2024-11-19 05:01 UTC, soletree commented on SniffMeet/SniffMeet/Source/SNMNetwork/Helper/URLRequest + append.swift
> +            self.setValue($1, forHTTPHeaderField: $0)
😂 감사합니다 추이...

2024-11-19 05:01 UTC, soletree commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
> +            print(error)
P3. Logger를 사용하면 더 좋을 것 같아요~~

2024-11-19 05:01 UTC, soletree commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseRequest.swift
> +            )
P1. 이 부분은 baseURL과 다르게 crash 가능성이 있을 것 같아요. .refreshToken 메서드를 호출하는 쪽에서 SupabaseConfig.session.refreshToken의 nil 여부를 판단해서 보내주는 방식은 어떠신가요? 
``` swift
case .refreshToken(let refreshToken): 
	// ,,, 중략 
```

2024-11-19 05:01 UTC, soletree commented on SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseUserResponse.swift
> +}
혹시 이친구는 어떻게 쓰이는 걸까요??

2024-11-19 10:10 UTC, Kelly-Chui commented on SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseUserResponse.swift
> +}
supabase에서 직접 커스텀할 수 있는 부분입니다. 
이름, 키워드, 프로필 이미지 등 정보를 담도록 저희가 서버에서 설정하면 돼요

2024-11-19 11:55 UTC, soletree requested changes

2024-11-19 11:55 UTC, soletree commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
> +        try UserDefaultsManager.shared.set(value: session.expiresAt, forKey: "expiresAt")
exiresAt만 UserDefaults에 저장하는 이유가 궁금합니다~

2024-11-19 11:55 UTC, soletree commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseRequest.swift
> +                    "grant_type": "refreshToken"
요거 혹시... `"\(refreshToken)"` 일까요?

2024-11-19 11:58 UTC, soletree approved these changes

2024-11-20 01:26 UTC, Kelly-Chui commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
> +        try UserDefaultsManager.shared.set(value: session.expiresAt, forKey: "expiresAt")
두 가지 이유가 있습니다.
큰 이유: Access, Refresh Token 처럼 보안에 민감한 정보가 아니라고 생각했습니다.
작은 이유: 키체인에는 Int 타입 저장이 안되어서 타입 캐스팅과 옵셔널 바인딩을 줄이기 위해서 입니다.

2024-11-20 01:27 UTC, Kelly-Chui commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
> +            print(error)
SNMLogger 사용하겠습니다~

2024-11-20 01:43 UTC, pearhyunjin approved these changes
고생 많으셨습니다! 
Auth 잘 완성된 것 같아요~ 👍👍
중간중간 공유해주신 내용들을 들은 상태로 코드를 보니 조금 더 이해하기 편했습니다.

2024-11-20 01:43 UTC, pearhyunjin commented on SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseRefreshResponse.swift
> +        case userMetadata = "user_metadata"
오 그럼 저희가 지정한 정보(이름, 키워드 등)는 이 user_metadata를 통해 한번에 가져와지는건가요?

2024-11-20 06:17 UTC, soletree commented on SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
> +        try UserDefaultsManager.shared.set(value: session.expiresAt, forKey: "expiresAt")
아 그렇겠네요 키체인 제가 String으로 막아두고 깜박하고 있었어요..ㅋㅋㅋ 
좋습니다~!

2024-11-20 07:28 UTC, merged

2024-11-20 07:52 UTC, Kelly-Chui commented on SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseRefreshResponse.swift
> +        case userMetadata = "user_metadata"
넵 Supabase 문서에서는 외래키를 사용해서 테이블을 만들어서 설정... 식으로 적혀있는데 지금 공부하고 있는 내용입니다!